services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: url_shortener_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - url_shortener

  nginx:
    image: nginx:1.25-alpine
    container_name: url_shortener_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - url_shortener

  db:
    image: postgres:16-alpine
    container_name: url_shortener_db
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - url_shortener

  redis:
    image: redis:7-alpine
    container_name: url_shortener_redis
    ports:
      - "6379:6379"
    networks:
      - url_shortener

networks:
  url_shortener:

volumes:
  pgdata:
