services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: url_shortener_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - url_shortener

  nginx:
    image: nginx:1.25-alpine
    container_name: url_shortener_nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - url_shortenerhttp://url_shortener_nginx/metrics

  db:
    image: postgres:16-alpine
    container_name: url_shortener_db
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: url_shortener
      POSTGRES_PASSWORD: secret123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - url_shortener

  redis:
    image: redis:7-alpine
    container_name: url_shortener_redis
    ports:
      - "6379:6379"
    networks:
      - url_shortener

# MONITORING SERVICES

  prometheus:
    image: prom/prometheus:latest
    container_name: url_shortener_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=30d'
    networks:
      - url_shortener
    restart: unless-stopped

  grafana:
      image: grafana/grafana:latest
      container_name: url_shortener_grafana
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin123
        - GF_USERS_ALLOW_SIGN_UP=false
        - GF_SERVER_ROOT_URL=http://localhost:3000
        - GF_INSTALL_PLUGINS=redis-datasource 
      volumes:
        - grafana-data:/var/lib/grafana
        - ./monitoring/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
        - ./monitoring/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
        - ./monitoring/dashboards:/var/lib/grafana/dashboards 
      depends_on:
        - prometheus
      networks:
        - url_shortener
      restart: unless-stopped

networks:
  url_shortener:

volumes:
  pgdata:
  prometheus-data:
  grafana-data:
