global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'url-shortner-monitoring'
    environment: 'develop'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:  ['localhost:9090']
        labels:
          service: 'prometheus'

  - job_name: 'laravel-app'
    metrics_path: '/metrics'        
    static_configs:
      - targets: ['app:8081']
        labels:
          service: 'laravel' 