server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        resolver 127.0.0.11 valid=10s;

        set $php_upstream app:9000;

        fastcgi_pass $php_upstream;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location = /healthz{
        access_log off;
        return 200 "OK";
        add_header Content-Type text/plain;
    }
}
